### ISSUE TITLE
setup hotspot without broadcasting SSID

### ISSUE THREAD

**Issue by johnoo** [Am0rphous/Create-WiFi-Hotspot-PowerShell#1]
Hello Thank you for this great script. Is there option / can you setup that one could setup hotspot without broadcasting SSID so clients should create wifi network and connect within their devices (android / pc)?

**Comment by Am0rphous** [comment]
Hi @johnoo !

Took me a while, but I've changed the source code.
I'm on Linux and MacOS atm so can't verify at the moment, but run the script and press '1' to set up a network. Choose "n" when asked if you want to broadcast the network.
